### ISSUE TITLE
Ver 6.0 - Preview cutoff in backend.

### ISSUE THREAD

**Issue by paaljoachim** [Really-Simple-Plugins/complianz-gdpr#327]
Hi

I am testing version 6.0 and hope that this is the place where you want feedback in regards to the new version.

The cutoff here of the preview looks like a bug.
![Screenshot 2021-12-31 at 10 27 06](https://user-images.githubusercontent.com/5323259/147815166-d819e084-c141-4172-894d-881ce883ec1d.jpg)

I noticed when hovering over the preview that the preview moved to the left so one can fully view the banner. Having it peak out halfway when not being hovered just feels like a bug. It just feels wrong and out of place. Like a painting hanging almost straight but not straight enough so that one has to just adjust it.

Please have the banner show fully. Yes it will cover options. One could of course just add a circle with a X at the top left corner of the banner so one can click the X and hide the banner. Which will automatically switch on the Hide preview toggle.

Btw do also include a test option to always show on frontend, so one can also go to the frontend and view what it looks like there as well.

**Comment by AertHulsebos** [comment]
Hi @paaljoachim,

Thanks for your feedback. You covered two topics we're currently discussing as well. It's between covering options or 'hiding' the banner until hovers. Both have their disadvantages, but we will strive for a solution that works for all screen sizes and makes the process less cumbersome, and hopefully deals with both disadvantages.

For the front-end previews, we actually started this conversation yesterday, because we need a solution to show the different banners (when GEOIP is enabled) without the need to change your location, which can be a challenge.

The latter is now on our backlog. The banner is something we deal with in 7.0. This update will only focus on user experience. For some reference as to an ETA, we will roll out 6.1 with Consent per Service in the next couple of weeks and follow-up with 6.2 & 6.3, which will be legal updates.

If you're interested in our first 7.0 efforts, let us know. We can invite you to the beta release program.

Regards Aert

**Comment by paaljoachim** [comment]
Hi @AertHulsebos Aert

> If you're interested in our first 7.0 efforts, let us know. We can invite you to the beta release program.

I am very interested in joining the beta release program. Thanks!

Happy New Year!

**Comment by Pollyreborn** [comment]
hjj
