### ISSUE TITLE
Using anonymizeIP not working

### ISSUE THREAD

**Issue by ccalislar35** [Really-Simple-Plugins/complianz-gdpr#349]
https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/196eec77ba37577775c87131b11bd4484dda2a55/cookie/class-cookie-admin.php#L2116

using "anonymizeIP" doesn't set the **_aip_** param which indicates that the use of analytics is anonymized
it should be look like this.
/collect?v=1&_v=j96&**_aip=1_**&a=1133263442&t=pageview&

after changing the used anonymizeIP to anonymize_ip after looking 
[how to set anonymize ip](https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization) 

it was properly set.
can you someone confirm this?

**Comment by AertHulsebos** [comment]
Hi @ccalislar35,

Thanks for your feedback. We recently switched to gtag.js for UA-* tracking codes as well, this indeed means the anonymizeIp:true should change to anonymize_ip:true if you have an isolated UA-* tracking code that isn't connected to GA4, since GA4 IP masking is the default for Google Analytics. 

It has now been updated in the main branches. Thanks again!

**Comment by ccalislar35** [comment]
Hi @AertHulsebos im not familiar the whole code but what's about this line does this need also to change? 
https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/eeeb255f0aff743fbc62adf8e7509e13f2e1fdb7/cookie/class-cookie-admin.php#L2409

**Comment by AertHulsebos** [comment]
Hi @ccalislar35,

anonymizeIp is still valid, but we need to account for different implementations. As I see it now we need to rework with more variables because you can use UA in different configs, and G-* is anonymized by default, so we need to check for the tracking code as well. This needs more testing, and will be done soon. The current merge was to fix the issue of our switch to gtag.js

Since GA4, there's also an instance where you can push UA-* data to GA4 in your GA dashboard. This in combination with consent mode, requires some research when we need to intervene and when Google anonymizes by default.

Thanks again for your input. I will reopen this so I can update you when we're done.

**Comment by rlankhorst** [comment]
The changes will be released on the 6.1 update, expected soon. The regex is just for detection, and will detect both versions of this variable. Thanks for reporting @ccalislar35.
