### ISSUE TITLE
Server throw a 520 error

### ISSUE THREAD

**Issue by Lofesa** [Really-Simple-Plugins/complianz-gdpr#350]
Hi @rlankhorst 
I have noticed that some times, when editing banner properties the server throws a 520 error in Cloudflare (unknow error).
In the server error log I have:
pread() read only 3575 of 3909 from ... in the banner-preview-2-optin.css file

Is possible that this file get changed/recreated on the fly  at the same time the file get served?
I don´t know if this happen in Apache server, I use nginx.
The solution maybe is recreated the file with a temporary extension and whe the new file is ok, then change it.
Some like a mv command in linux.

**Comment by rlankhorst** [comment]
We use NGINX with Cloudflare ourselves, but I haven't seen this yet. But yes, files get rewritten on style changes. When you change a banner property, the changed data is sent back to the server, and the preview file is regenerated. 
The code that handles this, looks like this:

```
if (file_exists("$upload_dir/complianz/css") && is_writable("$upload_dir/complianz/css")){
	$handle = fopen($file, "w");
	fwrite($handle, $css);
	fclose($handle);
}
```

Not sure if splitting it in two would help, as it adds two lines to otherwise compact code:

```
if (file_exists("$upload_dir/complianz/css") && is_writable("$upload_dir/complianz/css")){
	$temp = str_replace('.css', '.txt', $file);
	$temp_handle = fopen($temp, "w");
	fwrite($temp_handle, $css);
	fclose($temp_handle);
	unlink($file);
	rename($temp, $file);
}
```

I've create a branch with this code so you can try if it helps:
https://github.com/Really-Simple-Plugins/complianz-gdpr/tree/experiment-file-rewriting

What may be the problem, is that if you do a lot of changes fast, there may be several rewrites active at the same moment. 
So I think a better solution would be to lock the rewriting if one is currently active:

https://github.com/Really-Simple-Plugins/complianz-gdpr/tree/lock-file-on-css-generation

Let me know if one of these branches resolves your issue.

**Comment by Lofesa** [comment]
Hi
Sorry for comming to late here.
I have no tried the patch but go to try it in the next days and report here the result.
As a start I think the unlink is not needed as far as the rename command overwrites the file.
Alternatively I will try some like:

```
if (file_exists("$upload_dir/complianz/css") && is_writable("$upload_dir/complianz/css")){
	$handle = fopen($file, "c");
	if (flock($handle, LOCK_EX)) {
             ftruncate($handle, rand(1, filesize($file)));
             fwrite($handle, $data);
             flock($handle, LOCK_UN);
       }
	fclose($handle);
}
```

**Comment by rlankhorst** [comment]
a locking feature has been introduced in 6.1, which should resolve the issue. Let me know you run into any other issues.
