### ISSUE TITLE
Legal information

### ISSUE THREAD

**Issue by lkraider** [Really-Simple-Plugins/complianz-gdpr#367]
Is there a Legal Document for the plugin that can be shown to a Legal Team to approve the use of this plugin?

In particular, the terms of use and privacy of the plugin itself? It should include details such as: 
- does the plugin store personally identifiable information?
- does the plugin send any information to any external server?
- what are the privacy safeguards for any stored information?

and so on. Our legal team is wary of trusting an "open source" tool without these documents.

**Comment by Paapst** [comment]
Hi @lkraider ,
I suppose you are talking about the Free version right?

Unlike our premium Pro version, this plugin is actually free to use and is being delivered to you under a GPL v2 license. So that are the Terms of use for the Free version.
 The plugin is hosted locally, so it is entirely up to you to decide if you want to store personally identifiable information with the plugin. For the second question: yes, the plugin connects with cookiedatabase.org, as is being disclosed in the read me. 
Third question: once again, because the plugin is hosted by yourself, this is entirely up to your own IT environment.

If you want to use the plugin in a business environment, it would be a good option to consider one of our premium solutions. Please see our website where you can read the Terms of use for Complianz Premium [complianz
](https://complianz.io/legal/terms-of-use/)

**Comment by rlankhorst** [comment]
As to personally identifiable info: such info is not collected by the free plugin. If you use premium, there is an option to record given consent with the ip of the visitor. But that’s indeed up to you, and can be configured in the wizard.

**Comment by rlankhorst** [comment]
@lkraider does the above answer your questions?

**Comment by lkraider** [comment]
@rlankhorst Perfectly, thank you! In this case it seems the premium version makes sense for us, and we will be evaluating purchasing it! Thanks!
