### ISSUE TITLE
Plugin uses a lot of resources

### ISSUE THREAD

**Issue by paaljoachim** [Really-Simple-Plugins/complianz-gdpr#382]
Hey 

I am currently going through a few privacy /GDPR plugins for a tutorial on my WP tutorial site. Each have their own thing.

For instance Compianz just feels too complex. (I believe I have mentioned this some time ago.)
Making things harder than they should be. I would like to see an option to where one chooses what kind of site one is running. What are some low key options to make this easier? Keeping things simple.

Query Monitor resources time to load: 0.0731. It uses a lot of resources!

![Screenshot 2022-11-13 at 00 27 57](https://user-images.githubusercontent.com/5323259/201498580-773d4ffc-c7a1-403d-8ab9-623ad5af9a24.jpg)

Perhaps the plugin can start out with a simple wizard.
Saying something like.
What kind of site are you running?
Are you selling anything?
A signup form for a newsletter?
Etc. 5-6 quick and simple questions to start out with a simple Privacy banner.

Start out with a speedie setup to which the user can go back and fine tune anytime they want.
+ Open an Advanced / more options accordion/screen to go through additional options. Set it up. Then be able to export to another site that is similar. Being able to import and export.

**Comment by rlankhorst** [comment]
Hi @paaljoachim, Thanks for your feedback. Yes, we do have a simplification on the roadmap. First on the roadmap is implementation of a React back-end, which will give is more flexibility in the functionality, and a faster user experience. After that it's the improvement of the UX in terms of questions, order, and conditionality. 

As for the resources, do you maybe have debugging enabled? With debugging disabled, and front-end only, I'm on 0,0032. On the back-end on 0,013. If I enable debugging, a lot of additional checks fire, and the used resources increase significantly.

**Comment by paaljoachim** [comment]
Hey @rlankhorst Rogier
I am on a test site.
I activated the plugin Query Monitor and I am looking at the result in the Queries -> by Component backend.
On the frontend I have 0.0181. Second highest of what I have active on the site.

Btw I sent you a message on Slack.

**Comment by rlankhorst** [comment]
Hi @paaljoachim, yes, did the same thing, but different results, which is why I was wondering if you have debugging enabled. Because I get 0,0032 on the front-end. I'll do some research. Please note that if a cookiebanner is handled through a cloud service, like cookie yes for example, the load will shift to resource loading of the .js, and rendering of the webpage. So there will be less sql, but more third party .js files and client side code running. 

But I will see if we can optimise some more.

**Comment by rlankhorst** [comment]
@paaljoachim I made some changes:
- added an is_admin check to the cmplz_user_can_manage() function. Apparently the capability check is expensive, the is_admin check not so. 
- I've changed some wp_set_cache and wp_get_cache to set_transient and get_transient. It appears the transient function performs better than the wp_get_cache function, at least when it's not object cached, which is the case in most setups. If not object cached, the wp_set_cache lives only during the pageload, and has to be filled again on next pageload. This is not the case with transients. 

This has reduced the component time in Query Monitor to 0,0017. 

Let me know what your experience is with this branch:
https://github.com/Really-Simple-Plugins/complianz-gdpr/tree/performance

**Comment by paaljoachim** [comment]
Hey Rogier

It made a huge difference in the backend.
![Screenshot 2022-11-13 at 10 58 56](https://user-images.githubusercontent.com/5323259/201516206-90b32b31-42fa-4ead-a0d1-830bf092036e.jpg)

Frontend has about the same numbers.

So the changes you did made a difference.

**Comment by rlankhorst** [comment]
@paaljoachim that's good to hear! I'm curious what query monitor says is running if you click on the component. If I do this, I get 12 option selects, which amounts to 0,0016 in my latest test. I don't think I will be able to lower that much. If you're much higher, there might be something I'm missing, or which is setting specific. If you can post those select statements here I can look into those as well.

**Comment by paaljoachim** [comment]
Hi @rlankhorst 

I clicked on the component. It varies when I do a hard refresh.

![Screenshot 2022-11-13 at 11 56 00](https://user-images.githubusercontent.com/5323259/201518242-76df7ed6-d2a6-428e-ad90-5129736d0d71.jpg)

![Screenshot 2022-11-13 at 11 57 37](https://user-images.githubusercontent.com/5323259/201518259-74ee8fbc-0310-4633-ab60-34698515c3a0.jpg)

**Comment by rlankhorst** [comment]
@paaljoachim ideally, there should only be transients and options in the select list. I noticed cmplz_blocked_scripts listed in your screenshot, so I realised you've enabled consent per service. With that enabled, I did some more adjustments. With consent  per service enabled, I'm now down to 0,0014-0,0016 for the complianz component. Please not that the first refresh will populate the caches. Then on the second refresh the caches should be populated. 

There shouldn't be any 'UPDATE' statements on the front-end, and no selects other then transients and options.

**Comment by rlankhorst** [comment]
Fixed a bug I introduced in my last commit, which caused an error after the transient expires.

**Comment by paaljoachim** [comment]
Hi Rogier. Go ahead and close this issue when you feel it is time to do so. Have a nice Sunday evening!

**Comment by rlankhorst** [comment]
Thanks, the branch is added to our test queue, and will get merged soon.

**Comment by redtux** [comment]
Hi @rlankhorst, have your changes already been released? Just asking as I am having similar values in Query Monitor like Paal had in his initial comment to this issue.

**Comment by rlankhorst** [comment]
Not yet, I expect it in the next release, keep an eye on the changelog. Until then you can use this branche.

**Comment by marcbelletre** [comment]
Hi @rlankhorst,

I just tried the plugin for the first time. It does a fantastic job but there is indeed a big performance issue.  
On every single admin page the plugin generates ~70 queries. Here are all the results I get when loading the admin posts index page:

- ACF Pro: 9 queries
- Crop Thumbnails: 1 query
- Webp Express: 4 queries
- Yoast SEO: 4 queries
- Disable Comments: 1 query
- Complianz GDPR: 71 queries

It varies between 68 queries and 71 queries on each page load but the amount still seems huge compared to the other plugins

<img width="1543" alt="Capture d’écran 2023-12-15 à 18 17 42" src="https://github.com/Really-Simple-Plugins/complianz-gdpr/assets/6853334/bfa58157-cc52-4747-922b-60879ba3bde1">

The queries that are shown in purple by Query Monitor are the ones that are considered expensive (> 0.05s)  

There seems to be a lot of unnecessary expensive queries in the `cmplz_install_cookie_table` and `cmplz_install_cookiebanner_table` functions. As far as I know these functions should only be called when the plugin is activated using the [activation hook](https://codex.wordpress.org/Creating_Tables_with_Plugins#Calling_the_functions) instead of when the plugin is loaded.  

I didn't take the time to check the other queries but I think most of the `get_option` calls are unnecessary and could be avoided using the right hooks.

The performance branch is now far beyond the master branch so I guess there is no more plan to merge it but maybe this issue could be reopened so we can try to find solutions? I would be happy to help if I can.

**Comment by rlankhorst** [comment]
Did you try the current github master? It is completely different from the wordpress repo, and is waiting to be released. It should improve above stats.

**Comment by marcbelletre** [comment]
Hi @rlankhorst,

I confirm that the master branch makes a huge difference. 21 queries instead of 71 on the posts index page.  

There are still queries that I think could be avoided like these two calls to `update_option`. The `SHOW FULL COLUMNS` query seems particularly unnecessary and has a pretty big impact on performance.

<img width="1517" alt="Capture d’écran 2023-12-18 à 12 54 12" src="https://github.com/Really-Simple-Plugins/complianz-gdpr/assets/6853334/2f7058cc-f9b1-423b-875d-8f1f94eabebe">

Maybe it would make more sense to attach the `maybe_redirect_to_settings_page` function to the [plugin activation hook](https://developer.wordpress.org/plugins/plugin-basics/activation-deactivation-hooks/) instead of `admin_init` to avoid querying the database on each page load?

Anyway I'm happy to see that you're working on this. Great work, thank you!

**Comment by rlankhorst** [comment]
@marcbelletre thanks for checking, and for your input. The activation hook won't work for the redirect I'm afraid, as that has already happened at that point. The show full columns is something that is handled by WordPress itself, so don't have any influence on that part. 

Please note that:
- When WP_DEBUG and/or SCRIPT_DEBUG are enabled, the cmplz_version is appended with a timestamp, to ensure that some code always runs in that case. 
- options that are only loaded on the back-end have the 'autoload' attribute set to false. This ensures that these options are not preloaded on the front-end, thus keeping the preloaded options list small. The drawback is that these options require a separate query on the back-end, because they're not preloaded. 
- There is a strict separation between front-end code and back-end code, which ensures that a lot of code, like the redirect check, will never get executed when running on the front-end. 

This means that the performance measurements will improve if you disable debugging (both constants) and load the front-end only, then check the query monitor results again. Please reload the page to ensure that all caches have been 'warmed';
It will even get better when not logged in, but that is harder to measure, as you're not logged in then :). 

Setting the back-end options to autoload:false is something that is a relatively new WordPress best practice, which hasn't received wide adoption yet, but is an important step toward better performant ecosystem in my opinion.

**Comment by marcbelletre** [comment]
Thank you for taking the time to provide such a detailed answer.  
I confirm that when I'm not logged in the query monitor only shows 8 queries related to Complianz GDPR.

For now I'm going to use the master branch. I subscribed to the release notifications ;)

Cheers & thank you again for your work!
