### ISSUE TITLE
Youtube cookies description

### ISSUE THREAD

**Issue by pulsarinformatique** [Really-Simple-Plugins/complianz-gdpr#409]
Hello

Hi
Even If I refuse the cookies on https://www.fonds-metro.org/ I can still see the browser load some youtube cookies :

![image](https://github.com/Really-Simple-Plugins/complianz-gdpr/assets/10794564/67c91501-a7ed-4ca1-b3da-8a0d041c58fa)

Is that normal please?

thanks

**Comment by pulsarinformatique** [comment]
Hi
Can you answer please?
thanks

**Comment by rlankhorst** [comment]
I think this is caused by your background video, which is loaded by Elementor through their javascript core file. 
As Elementor does not conform to the wp-consent-api, you can use a custom integration to handle this:

https://github.com/Really-Simple-Plugins/complianz-integrations/blob/master/elementor-background-video.php

As this is a development repository, it is not monitored regularly for support requests. To ensure a fast response, it is better to contact our support on the WordPress forum, or directly through our website, https://complianz.io/support

**Comment by pulsarinformatique** [comment]
Hi
Thanks but on https://complianz.io/support I can't see any way to ASK such a question even when I'm a premium user
thanks for your help

**Comment by rlankhorst** [comment]
@pulsarinformatique if you scroll down a bit you will see a "log a support ticket" heading, which is where you can ask any question you want, for both free and premium users.

**Comment by pulsarinformatique** [comment]
thanks !
