### ISSUE TITLE
Elementor issue as from 7.x

### ISSUE THREAD

**Issue by robbygeybels** [Really-Simple-Plugins/complianz-gdpr#419]
The latest 6.x didnt give any issues, but when 7.x has been installed I have some strange JS behaviour as soon as the cookie gets accepted.  I'll set the latest version again on adminbuddy.be, there is a FAQ section at the bottom on the homepage. I also have issues on other website, where for example on mobile the menu doesn't open anymore etc. But the toggle shows that something goes wrong very clearly

**don't accept cookies**: FAQ works as expected
**accepted cookies:** first time toggle works in faq, but after that weird behaviour (open and close instantly, or opening/closing multiple times with 1 click)

**Comment by jarno-vos** [comment]
Hi @robbygeybels,

Your issue is most-likely caused by a specific integration that has been activated under _Complianz -> Integrations -> Services / Plugins_, rather than it being a bug in the plugin introduced with version 7.x.

In your case, the _Ultimate Addons for Elementor_ integration seems to be the most-likely culprit. Deactivating it under _Complianz -> Integrations -> Services / Plugins_ should resolve the described issue.

Kind regards, Jarno
